# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Experience"
  pageRef = "experience"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40
