# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

replyByEmail = false

disableImageOptimization = false
disableTextInHeader = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showReadingTime = false
  showWordCount = false
  showBreadcrumbs = true
  showPagination = true
  showTableOfContents = false
  showTaxonomies = false
  showHero = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  orderByWeight = true
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
